### ISSUE TITLE
DateTimeSerializerBase doesn't use WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS with `java.sql.Timestamp`

### ISSUE THREAD

**Issue by hadrienk** [FasterXML/jackson-modules-java8#10]
When converted using DateTimeSerializerBase, java.sql.Timestamp instances are not written in nanoseconds, even if the WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS feature is enabled.

I found this error doing the following:

ObjectMapper mapper = new ObjectMapper();
mapper.registerModule(new JavaTimeModule());
mapper.configure(SerializationFeature.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS, true);
mapper.configure(DeserializationFeature.READ_DATE_TIMESTAMPS_AS_NANOSECONDS, true);
mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, true);
mapper.convertValue(new Timestamp(1456412409000), Instant.class)

**Comment by hadrienk** [comment]
I wrote this issue on the [databind project](https://github.com/FasterXML/jackson-databind/issues/1499) by mistake.

**Comment by cowtowncoder** [comment]
I am not sure this is possible to implement in backwards compatible manner; although I guess use of floating-point representation might work?

**Comment by cowtowncoder** [comment]
Actually support does need to be in `jackson-databind` so I'll close this, re-open the other one.
I am cautiously positive I'll actually have time to try to implement support.
