### ISSUE TITLE
Any annotation to enable java8 in SpringBoot?

### ISSUE THREAD

**Issue by isur3n** [FasterXML/jackson-modules-java8#102]
I am developing a micro-service that reads JSon from file system and converts them in to PoJos. I am using SpringBoot and hence ObjectMapper comes AutoWired with it.

Now, I would like to import object with field as LocalDateTime and for it, I need to add few annotations as mentioned below.

    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
    @JsonSerialize(using = LocalDateTimeSerializer.class)
    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
    private LocalDateTime dateCreated;

So, I wanted to know if there is any annotation available which can trigger java8 enhancements to SpringBoot instance of ObjectMapper for whole application without me having to explicitly call it?

I have referred your guide and can see there are 2 ways to explicitly enable java8 enhancements.

```
ObjectMapper mapper = new ObjectMapper()
   .registerModule(new ParameterNamesModule())
   .registerModule(new Jdk8Module())
   .registerModule(new JavaTimeModule()); // new module, NOT JSR310Module
```

Or

```
ObjectMapper mapper = new ObjectMapper();
mapper.findAndRegisterModules();
```

If there is any annotation that can do it for SpringBoot instance, it will be great. Will reduce explicit Serializer/Deserializer annotations.

Much appreciate help.

**Comment by RemusRD** [comment]
By default, Spring boot will register automatically the common modules you would want to register, like KotlinModule or Java8Module, you just need to add the dependency to your project, if you want to further customize the ObjectMapper, you can inject yourself the `Jackson2ObjectMapperBuilder` and customize it as a configuration, see [Jackson2ObjectMapperBuilder](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/http/converter/json/Jackson2ObjectMapperBuilder.java)

**Comment by cowtowncoder** [comment]
Also, in future please do not file Spring Boot QUESTIONS o Jackson ISSUE TRACKER. This is not what it is here for, and will add noise to already active system.
Jackson groups like

https://groups.google.com/forum/#!forum/jackson-user

are better places to ask for help (and wrt Spring Boot I think there are other resources).
