### ISSUE TITLE
`LocalTime` should generate "time" schema instead of "date-time"

### ISSUE THREAD

**Issue by jaisonpjohn** [FasterXML/jackson-modules-java8#105]
When I am generating Swagger spec for a LocalTime Java Object I wanted to get
`"format" : "time"` instead of `"format" : "date-time"`.
otherwise it was tripping off a codegen-from-swagger on consumer side.

I have submitted a PR for the same https://github.com/FasterXML/jackson-modules-java8/pull/104

**Comment by jaisonpjohn** [comment]
@cowtowncoder When you get a chance, could you please take a look. Thanks for your time

**Comment by cowtowncoder** [comment]
@jaisonpjohn ah sorry for skipping this. Will add to my (somewhat long, arguably... :) ) W-I-P list

**Comment by jaisonpjohn** [comment]
@cowtowncoder No worries, Thank you.

**Comment by cowtowncoder** [comment]
@jaisonpjohn Finally found time to finish this: I ended up doing manual merge to get this in 2.10, and added some baseline unit testing (just for this and couple of other types). Thank you again for submitting this, it'll get in 2.10.0.
