### ISSUE TITLE
Disabling WRITE_DATES_AS_TIMESTAMPS not working?

### ISSUE THREAD

**Issue by ddyangz** [FasterXML/jackson-modules-java8#11]
According to the /datetime/ summary, java.time.offsetDateTime objects should serialize out to ISO-8601 strings simply by disabling the SerializationFeature#WRITE_DATES_AS_TIMESTAMPS feature?

I've tried to do this in two different ways in the JacksonConfig class:

```
ObjectMapper mapper = new ObjectMapper()
            .registerModule(new ParameterNamesModule())
            .registerModule(new Jdk8Module())
            .registerModule(new JavaTimeModule())
            .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
```

```
@Bean
@Primary
public ObjectMapper objectMapper(Jackson2ObjectMapperBuilder builder) {
        ObjectMapper objectMapper = builder.createXmlMapper(false).build();
        objectMapper
                .registerModule(new ParameterNamesModule())
                .registerModule(new Jdk8Module())
                .registerModule(new JavaTimeModule())
                .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
        return objectMapper;
}
```
           
In both cases, serialized offsetDateTime objects continue to be printed in nanosecond timestamp format (i.e. "expiresOn":1486138656.853000000).

Only by actually declaring @JsonFormat can I get them to print out in ISO-8601 string.

Is anyone else having this issue?

**Comment by bendem** [comment]
That's most likely a problem coming from spring configuration.

+ Check there is no version conflict (pulling different version of jackson)
+ Use application properties to configure jackson (`spring.jackson.serialization.write-dates-as-timestamps=false`)
+ If the 2 solutions above do not work, start removing your `@Enable___` annotations one by one, they sometime override your configuration.

**Comment by ddyangz** [comment]
Thanks. 
#2 (adding spring.jackson.serialization.write-dates-as-timestamps=false to application properties) fixed it. I I guess spring jackson properties overloads the objectMapper of the Jackson Configuration.

**Comment by cowtowncoder** [comment]
Assuming this gets resolved as described, as Spring config is out of Jackson's hands.
But if Jackson-side problems exist, may be reopened with a standalone test.

**Comment by Dienry** [comment]
Where do you put this in your code?

ObjectMapper mapper = new ObjectMapper()
            .registerModule(new ParameterNamesModule())
            .registerModule(new Jdk8Module())
            .registerModule(new JavaTimeModule())
            .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);

Thanks!

**Comment by bendem** [comment]
Nowhere, you aren't supposed to instantiate your `ObjectMapper` yourself if you are using spring-boot. See [my earlier answer](https://github.com/FasterXML/jackson-modules-java8/issues/11#issuecomment-277648027).

**Comment by tibuurcio** [comment]
Hey guys, sorry for reopening this issue.

I've tried all of the solutions above to solve this problem but my Spring Controller keeps serializing `LocalDateTime` with it's properties instead of `YYYY-MM-DD...`

I think it could be a version conflict since I'm using other dependencies, but I don't know how to check for this. Can anyone shine a light on how can I do it?

**Comment by ddyangz** [comment]
Make sure you have this in your application.yml:

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
      wrap-root-value: true

Keep the 3 noted in project title page in dependencies:
"com.fasterxml.jackson.module:jackson-module-parameter-names:{version}"
"com.fasterxml.jackson.datatype:jackson-datatype-jdk8:{version}"
"com.fasterxml.jackson.datatype:jackson-datatype-jsr310:{version}"

**Comment by cogito-abhijeet** [comment]
If you are using swagger with spring boot and your date is Date is always getting serialised as long,  and SerializationFeature.WRITE_DATES_AS_TIMESTAMPS &  spring.jackson.serialization.write-dates-as-timestamps=false
are not helping, below solution worked for me. Add it to your class annotated with @SpringBootApplication: 


    @Autowired
    private RequestMappingHandlerAdapter handlerAdapter;
    
    @EventListener
    public void handleContextRefresh(ContextRefreshedEvent event) {
        handlerAdapter
                .getMessageConverters()
                .stream()
                .forEach(c -> {
                    if (c instanceof MappingJackson2HttpMessageConverter) {
                        MappingJackson2HttpMessageConverter jsonMessageConverter = (MappingJackson2HttpMessageConverter) c;
                        ObjectMapper objectMapper = jsonMessageConverter.getObjectMapper();
                        objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
                    }
                });
    }

Actual issue: SerializationFeature.WRITE_DATES_AS_TIMESTAMPS value is not read from spring configuration file which need to be set false in order  to covert long value while serialisation.

**Comment by kupci** [comment]
> Actual issue: SerializationFeature.WRITE_DATES_AS_TIMESTAMPS value is not read from spring configuration

Should there be, or is there, an issue filed with Spring for this?

**Comment by MisterDurden** [comment]
@cogito-abhijeet 
Hi, your solution worked but is there any way to achieve this without the EventListener annotation as we have certain restriction on startup time and I was looking for a way to configure this without using the EventListener?

> Actual issue: SerializationFeature.WRITE_DATES_AS_TIMESTAMPS value is not read from spring configuration file which need to be set false in order  to covert long value while serialisation.
Is this issue reported to Spring?
