### ISSUE TITLE
Inconsistent Instant serialization JDK10/JDK8

### ISSUE THREAD

**Issue by vghero** [FasterXML/jackson-modules-java8#112]
We recently switched from JDK8 to JDK10 and encountered some serialization changes when it comes to `Instant` using jackson 2.9.x. Before, it was rendered with milliseconds, but now nanos are used. Since this affects API contracts, we wonder if this is a known issue. See the example code below:

```
    public static void main(String[] args) throws JsonProcessingException {

        ObjectMapper mapper = new ObjectMapper().setSerializationInclusion(Include.NON_NULL)
                .registerModule(new JavaTimeModule())
                .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false)
                .configure(SerializationFeature.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS, false)
                .configure(DeserializationFeature.READ_DATE_TIMESTAMPS_AS_NANOSECONDS, false)
                .configure(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE, false);

        // JDK10: "2019-05-15T10:14:51.620623Z"
        // JDK8: "2019-05-15T10:15:49.003Z"
        System.out.println(mapper.writeValueAsString(Instant.now()));
    }
```

I tried to find related issues or documentation regarding JDK10 `Instant` rendering problems, but couldn't find anything related to it.

**Comment by cowtowncoder** [comment]
Behavior should not vary, as Jackson does not change its behavior based on JDK version.
So this sounds like some kind of bug. I assume same would be the case wrt JDK11?

**Comment by cowtowncoder** [comment]
Ok two things:

1. By default `Instant` serialization relies on `Instant.toString()`, so difference would be within JDK implementation, independent of Jackson
2. Test to show the issue should use specified time point (and not `Instant.now()`) as the example suggests there is actual correctness issue (values are different, not just wrt accuracy) -- unless that's just cut'n paste artifact.

So, at this point unfortunately I can not reproduce. Since JDK10 is obsolete too (JDK 8 and 11 are Long-Term Support versions, 9 and 10 are not), it would also be good to know how JDK11 handles this.

**Comment by vghero** [comment]
Hey.

You're absolutely right :)!

With https://bugs.openjdk.java.net/browse/JDK-8068730 they implicitly changed the behavior of `Instant.now()` that now takes higher clock precisions (e.g. microseconds) into account and hence also `toString()` looks different in JDK8+ in comparison to JDK8. So as you already pointed out, no problem of jackson directly, but the underlying JDK. Rendering of a "fixed" initialized `Instant` is rendered by jackson the same, no matter what JDK.

For us that means, strictly speaking, we have to explicitly define the format of `Instant` rendering instead of relying on jackson's default `toString()` rendering - which varies on different JDKs.

If someone is interested, I attached a maven project that demonstrates the behavior. Running it with JDK8 works, but fails with 10+11.

Thanks for taking your time looking into it and sorry for any inconvenience! This can be closed then.

[jackson-test.zip](https://github.com/FasterXML/jackson-modules-java8/files/3262073/jackson-test.zip)
