### ISSUE TITLE
Custom LocalTimeSerializer gets overwritten

### ISSUE THREAD

**Issue by dankito** [FasterXML/jackson-modules-java8#115]
We have a custom LocalTimeSerializer:

```
public class TimeProgramTimeSerializer extends LocalTimeSerializer {

	public TimeProgramTimeSerializer() {
		// Default doesn't cut it for us.
		super(DateTimeFormatter.ofPattern("HH:mm"));
	}

}
```

And set it like this:
```
        @JsonSerialize(using = TimeProgramTimeSerializer.class)
	protected LocalTime startTime;
```

Before version 2.9.x everything worked fine. Starting with 2.9.0 our custom serializer gets ignored.

Issue is this logic in JSR310FormattedSerializerBase.createContextual()

```
   public JsonSerializer<?> createContextual(SerializerProvider prov, BeanProperty property) throws JsonMappingException {
        JsonFormat.Value format = findFormatOverrides(prov, property, handledType());
        if (format != null) {
            // ...

            JsonFormat.Shape shape = format.getShape();
            // ...

            // as shape != _shape a new LocalTimeSerializer gets created and our custom serializer therefore dismissed
            JSR310FormattedSerializerBase<?> ser = this;
            if ((shape != _shape) || (useTimestamp != _useTimestamp) || (dtf != _formatter)) {
                ser = ser.withFormat(useTimestamp, dtf, shape);
            }
            // ...

            return ser;
    }
```

In JSR310FormattedSerializerBase constructor _shape gets set to null.

findFormatOverrides() returns MapperConfig.EMPTY_FORMAT where shape is Shape.ANY.

Therefore _shape and MapperConfig.EMPTY_FORMAT.shape don't match even though they both have the default values. ser.withFormat() then creates a new LocalTimeSerializer and our custom serializer gets ignored.

So please make the defaults for _shape and MapperConfig.EMPTY_FORMAT.shape match, so that custom serializers don't get overridden.

**Comment by cowtowncoder** [comment]
Thank you for reporting the issue and troubleshooting to see what causes it. I hope to address this in near future -- but there are a few issues to work on so it may take a while.

**Comment by cowtowncoder** [comment]
Unfortunately I am not able to reproduce this with either 2.9 or 2.10, and would need a full reproduction.

**Comment by cowtowncoder** [comment]
Can not reproduce: may be reopened with a test case.
