### ISSUE TITLE
Deserialization of `ZonedDateTime` may lose zone information

### ISSUE THREAD

**Issue by hohwille** [FasterXML/jackson-modules-java8#118]
On Deserialization of ZonedDateTime the ZoneId is added as offset and lost resulting in "1999-12-31T23:59:59+02:00" being deserialized as "1999-12-31T21:59:59Z[UTC]".
I traced it down to the root which is here:
https://github.com/FasterXML/jackson-modules-java8/blob/master/datetime/src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/InstantDeserializer.java#L209

IMHO one would need to use `ZonedDateTime.parse(CharSequence)` to properly deserialize `ZonedDateTime`.

See also https://github.com/devonfw/devon4j/issues/116

**Comment by cowtowncoder** [comment]
Did you try disabling `DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE`? That was added to allow control over whether `TimeZone` is to be unified or not.

**Comment by cowtowncoder** [comment]
I think that this might be good issue for new contributors to investigate.

**Comment by kupci** [comment]
@hohwille Did disabling the `DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE` solve the issue for you? That looks like it should work, though I notice there isn't any documentation on this setting, or at least I couldn't find it, so I added a 'Documentation Needed' label to this item.

**Comment by kupci** [comment]
Found the documentation: https://github.com/FasterXML/jackson-databind/wiki/Deserialization-Features

**Comment by kupci** [comment]
With the update to the README, I think this can be closed. There are also a bunch of tests that exercise the functionality (@see `TestZonedDateTimeSerialization`) though if additional tests are helpful, please re-open and they can be added.

**Comment by hohwille** [comment]
Sorry for the late response but I can confirm that your suggestion fixed the issue. Thanks for the hint and great that you also updated to docs 👍
