### ISSUE TITLE
MonthDayDeserializer cannot be instantiated

### ISSUE THREAD

**Issue by karlmuscat** [FasterXML/jackson-modules-java8#125]
Hi. I have encountered an issue when using the MonthDayDeserializer. Usage:

>@JsonFormat(pattern = "MMdd")
    @JsonSerialize(using = MonthDaySerializer.class)
    @JsonDeserialize(using = MonthDayDeserializer.class)
    private MonthDay localDate;

The error generated is:
>"Error creating bean with name 'com.fasterxml.jackson.datatype.jsr310.deser.MonthDayDeserializer': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.time.format.DateTimeFormatter' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}"

From some investigation, it seems that the deserializer has one constructor that expects a DateTimeFormatter as parameter and is missing the default constructor. Instantiation is failing due to the missing default constructor.

**Comment by cowtowncoder** [comment]
This should be easy to solve: do not use `@JsonSerialize` and `@JsonDeserialize` annotations, and use Java 8 datetime module to register handlers. (De)serializer implementations are not meant to be used via annotations, as general rule.

**Comment by karlmuscat** [comment]
My understanding is that by using the JavaTimeModule, you would not have control over the formatter used (given that it uses MonthDayDeserializer.INSTANCE). Is that correct? 

The other option would be to manually register the de/serializer with my preferred formatter (using the provided constructor). But then how could I have different formats for the same de/serializer?

**Comment by cowtowncoder** [comment]
`@JsonFormat` should be used always regardless of the way deserializer is registered (assuming deserializer has support -- since it is up to (de)serializer to support, coverage is sometimes uneven).
But it does not differ across different methods of creating deserializer instance.

**Comment by cowtowncoder** [comment]
Looking at `MonthDaySerializer`, it does accept formatter via `@JsonFormat`, so unless there is a bug it should work without registration. Closing.
