### ISSUE TITLE
`configureAbsentsAsNulls` not working for primitive Optionals like `OptionalInt`

### ISSUE THREAD

**Issue by lrpg** [FasterXML/jackson-modules-java8#13]
```
type.isTypeOrSubTypeOf(Optional.class)
```
is evaluated to true with Optional\<Integer\> while
it is evaluated to false with OptionalInt because OptionalInt is not a type or subtype of Optional\<\>

Same goes for OptionalDouble and OptionalLong

https://github.com/FasterXML/jackson-modules-java8/blob/master/datatypes/src/main/java/com/fasterxml/jackson/datatype/jdk8/Jdk8BeanSerializerModifier.java#L26

**Comment by cowtowncoder** [comment]
What is the bug here? `Optionalnt` is indeed not a sub-type of `Optional` in Java world. You may think of them as related, but from Java (JVM) type system perspective they are not related.

But perhaps you have an actual problem, and above is just explaining why you think that might occur? If so, please describe the problem first.

**Comment by lrpg** [comment]
`Jdk8Module.configureAbsentsAsNulls`  has an effect on `Optional<>` but not `OptionalInt`, `OptionalLong` and `OptionalDouble`, which is confusing and contradictory according to the javadoc of the `Jdk8Module.configureAbsentsAsNulls`: 
_Configuration setting that determines whether `Optional.empty()` is considered "same as null" for serialization purposes; that is, to be filtered same as nulls are. If enabled, absent values are treated like nulls; if disabled, they are not. In either case, absent values are always considered "empty"._

The logic around `Optional` happens in **Jdk8BeanSerializerModifier** at **type.isTypeOrSubTypeOf(Optional.class)** as specified above.

**Comment by cowtowncoder** [comment]
@lrpg thank you for clarification, makes sense. I updated title to reflect what I think is the issue.

**Comment by cowtowncoder** [comment]
Ok required bit bigger changes but works now, for 2.9.0(.pr2).
