### ISSUE TITLE
Prevent deserialization of "" as `null` for `Duration`, `Instant`, `LocalTime`, `OffsetTime`, and `YearMonth` in "strict" (non-lenient) mode

### ISSUE THREAD

**Issue by kupci** [FasterXML/jackson-modules-java8#138]
For the java.time classes Duration, Instant, LocalTime, OffsetTime and YearMonth, an empty string is mapped to null by the associated deserializer, for example DurationDeserializer, InstantDeserializer, etc. So something like {"date": null} can't be distinguished from {"date": ""}. From the view of a strict API, the latter is an error.

It would be good to add some feature to treat empty string as invalid format, so that the associated deserializer (DurationDeserializer, etc) could report this as an error instead of mapping to null. This capability should be noted in the documentation.

This issue is related to issue #114 which was fixed for LocalDate and LocalDateTime. However, the fix is still required for the java.time types listed here.

**Comment by cowtowncoder** [comment]
Ok, merging to `master` was some work.. .but is done.

I did however uncover one concern: #68 fix was undone by this change (2 tests broke). I think I will just comment out those tests on short term, but need to figure how these settings should work together.

**Comment by kupci** [comment]
Cool, and I will take a look at #68. Lenient is set by default so empty string should pass through, so probably something else..

**Comment by cowtowncoder** [comment]
I think what happened was more along the lines that I had added new handling in `master`, but due to changes from 2.11, merging, those are overridden. It's fine as nothing is released, and more a question of what should be the overall algorithm for determining acceptance. And not so much a bug introduced.
