### ISSUE TITLE
Let reuse of Instant serializer provided by JavaTimeModule

### ISSUE THREAD

**Issue by askvortsov** [FasterXML/jackson-modules-java8#14]
I'd like ObjectMapper write most Temporals as Strings (thus disabling WRITE_DATES_AS_TIMESTAMPS), but for Instants I'd like to use timestamps.
JSR310FormattedSerializerBase has the ability to override timestamp mode, but it is controlled by Shape annotation only.
Can we have a constructor for [InstantSerializer.java](/FasterXML/jackson-modules-java8/blob/master/datetime/src/main/java/com/fasterxml/jackson/datatype/jsr310/ser/InstantSerializer.java) (and maybe other descendants of JSR310FormattedSerializerBase?) that allows setting _useTimestamp?

**Comment by cowtowncoder** [comment]
While this can be done, main idea with 2.8 and beyond is to allow per-type configuration of `JsonFormat.Value` to use, using so-called config overrides:

    mapper.configOverride(Instant.class).setFormat(JsonFormat.Value.forShape(Shape.STRING);

Aside from that open to PRs for changes.

**Comment by askvortsov** [comment]
Oh, I should have reread Jackson docs, haven't dine this in long time. :)
Setting override does exactly what I want!
