### ISSUE TITLE
LocalDateTime double quotation on (de)serialization

### ISSUE THREAD

**Issue by osahner** [FasterXML/jackson-modules-java8#146]
### jackson v2.10.0

**LocalDateTime** values get wrapped in additional `"` quotes on serialization and fail deserialization if not quoted (e.g.` "\"2014-12-20T02:30:10\""`). 

```java
  @Test
  void serializingJava8Date() throws Exception {
    ObjectMapper mapper = new ObjectMapper();
    mapper.registerModule(new JavaTimeModule());
    mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
    LocalDateTime date = LocalDateTime.of(2014, 12, 20, 2, 30, 10);
    String result = mapper.writeValueAsString(date);
    assertEquals(result, "\"2014-12-20T02:30:10\"");
    LocalDateTime date2 = mapper.readerFor(LocalDateTime.class).readValue("\"2014-12-20T02:30:10\"");
    assertEquals(date, date2);
  }
```

**Comment by cowtowncoder** [comment]
Thank you for reporting this. I assume this is different from earlier versions (2.9.x)?
Value quotation itself is required as JSON requires that for all String values, but not 2 sets of quotes, if that is what happens.

**Comment by osahner** [comment]
https://github.com/osahner/jackson-localdatetime-doublequotes.git

**Comment by kupci** [comment]
The other set of quotes is for the test fixture, so I think this is working as expected. It works the same in 2.9.x, and the tests are similar in [LocalDateTimeSerTest](https://github.com/FasterXML/jackson-modules-java8/blob/d1c4048868023894eedfa13ba21b3c964bd20401/datetime/src/test/java/com/fasterxml/jackson/datatype/jsr310/ser/LocalDateTimeSerTest.java#L106).

**Comment by cowtowncoder** [comment]
Yeah I don't really see a problem here. JSON String values must be quoted, and test as included passes as expected.

**Comment by osahner** [comment]
my bad - sorry! found my error!
