### ISSUE TITLE
Optional<Long> and OptionalLong deserialization are not consistent when deserializing from String.

### ISSUE THREAD

**Issue by lrpg** [FasterXML/jackson-modules-java8#15]
Examplewith:  `{ "someString" : "9223372036854775807" }`
`Optional<Long>` successfully deserializes while LongDeserializer
`OptionalLong` does not.

It is due to the first deserializing with `NumberDeserializers.LongDeserializer` using `_parseLong(p, ctxt)` 
while the latter is deserialized with `OptionalLongDeserializer` using `jp.getLongValue`.

**Comment by cowtowncoder** [comment]
Yes, I can see the problem here. Thank you for reporting this.

**Comment by cowtowncoder** [comment]
Interestingly enough, only Long variant appears to fail with 2.8, not int or double. Would have expected more coercion fails.
