### ISSUE TITLE
Please apply the license properly

### ISSUE THREAD

**Issue by enepomnyaschih** [FasterXML/jackson-modules-java8#159]
Could you please properly apply Apache 2.0 license boilerplate to all source files of "datatypes" module as per APPENDIX section in https://github.com/FasterXML/jackson-modules-java8/blob/master/LICENSE? I'll appreciate if you can do this for legacy version 2.9 of the module as well. Thank you.

**Comment by cowtowncoder** [comment]
Nope.

**Comment by enepomnyaschih** [comment]
Do you realize that it prevents developers from using the library?

**Comment by cowtowncoder** [comment]
@enepomnyaschih I don't think it does, based on experience from past 12 years for this library. There is no reason to pollute source code files with boiler-plate crap that adds literally no value.
