### ISSUE TITLE
Problem in serializing negative Duration values

### ISSUE THREAD

**Issue by jpsyri** [FasterXML/jackson-modules-java8#165]
When `SerializationFeature.WRITE_DURATIONS_AS_TIMESTAMPS` is true, `Duration`s with negative value get serialized wrong. For example `Duration.ofMillis(-1)` gets serialized as "-1.999000000"

Problem seems to be in `DurationSerializer` where following  code is used for serializing

```
                generator.writeNumber(DecimalUtils.toBigDecimal(
                        duration.getSeconds(), duration.getNano()
                ));
```
However `Duration` internally stores duration in format where seconds part basically contains `floor(duration)` and nanoseconds part contains offset from that value to the actual duration. So n case of duration of -1 millisecond, the seconds part value will be -1 and nanoseconds part will be 999000000. `getSeconds()` and `getNano()` return values according to that internal representation, which leads to the problem.

**Comment by kupci** [comment]
Will take a look, but in the meantime, what release are you seeing this in, and what flags do you have set. (If you have a test case, that would be great.) Taking a quick look, the `DurationSerializer` _should_ be using millis, unless otherwise specified. 

However, we happened to just be discussing this the other day and I think the nanos flag `WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS` is (probably incorrectly) defaulting to true:
 ```
       if (useTimestamp(provider)) {
            if (useNanoseconds(provider)) {
                generator.writeNumber(DecimalUtils.toBigDecimal(
                        duration.getSeconds(), duration.getNano()
                ));
            } else {
                **generator.writeNumber(duration.toMillis());**
            }

```
https://github.com/FasterXML/jackson-modules-java8/blob/ff084de89a7a1f2a0f857b246ad4eb46cbfc6f60/datetime/src/main/java/com/fasterxml/jackson/datatype/jsr310/ser/DurationSerializer.java#L82

**Comment by jpsyri** [comment]
I think we are using 2.10.2 (can't check at the moment). Only feature we have set is the "write datetimes as timestamps"- one. I however did run the serialization on debugger while investigating and both if-conditions on that snippet were evaluating to true, but I didn't really think about that further

I might be able to provide test case tomorrow

**Comment by kupci** [comment]
> and both if-conditions on that snippet were evaluating to true,

Would you please try setting the SerializationFeature `WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS` to false and retry, and see if that resolves the issue? You can see some examples here:

https://github.com/FasterXML/jackson-modules-java8/blob/master/datetime/src/test/java/com/fasterxml/jackson/datatype/jsr310/ser/DurationSerTest.java

**Comment by jpsyri** [comment]
I created some test cases at https://github.com/jpsyri/jackson-duration-serialization

Disabling the `WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS` seems to result serialization as whole milliseconds as expected: `Duration` of -1 milliseconds is serialized as "-1". That feature enabled (including when state of that feature is not explicitly changed) results "-1.999000000"
