### ISSUE TITLE
ZonedDateTime can't be deserialized 

### ISSUE THREAD

**Issue by mabujaber** [FasterXML/jackson-modules-java8#167]
I'm using spring boot 2.2.5 and I tried to deserialized ZonedDateTime provided by AWS SQS
 and got the same exception. 

the date format I got from amazon as `2020-03-23T09:21:00.353Z`

and the exception 
```Could not read JSON: Cannot construct instance of `java.time.ZonedDateTime` (no Creators, like default construct, exist): no String-argument constructor/factory method to deserialize from String value ('2020-03-23T09:21:00.353Z')```

I explicitly make jackson as 2.9

**Comment by kupci** [comment]
Would you please try this with the [deserialization ](https://github.com/FasterXML/jackson-databind/wiki/Deserialization-Features)feature `UNWRAP_SINGLE_VALUE_ARRAYS` enabled? For example:
```
        ZonedDateTime value = newMapper()
    			.readerFor(ZonedDateTime.class)
               .with(DeserializationFeature.UNWRAP_SINGLE_VALUE_ARRAYS)
    			.readValue("[\"2020-03-23T09:21:00.353Z\"]");
```

**Comment by cowtowncoder** [comment]
This sounds like you didn't actually register JAva 8 date/time module?

**Comment by mabujaber** [comment]
> This sounds like you didn't actually register JAva 8 date/time module?
> 
> @kupci if input comes as `String`, that setting should not matter: it only unwraps JSON Arrays.

The Java 8 module is registered by default in a spring boot 2 projects and later

**Comment by mabujaber** [comment]
> Would you please try this with the [deserialization ](https://github.com/FasterXML/jackson-databind/wiki/Deserialization-Features)feature `UNWRAP_SINGLE_VALUE_ARRAYS` enabled? For example:
> 
> ```
>         ZonedDateTime value = newMapper()
>     			.readerFor(ZonedDateTime.class)
>                .with(DeserializationFeature.UNWRAP_SINGLE_VALUE_ARRAYS)
>     			.readValue("[\"2020-03-23T09:21:00.353Z\"]");
> ```

here is my message
```
{
  "notificationType": "Bounce",
  "bounce": {
    "bounceType": "Permanent",
    "bounceSubType": "Suppressed",
    "bouncedRecipients": [
      {
        "emailAddress": "blacklist@simulator.amazonses.com",
        "action": "failed",
        "status": "5.1.1",
        "diagnosticCode": "Amazon SES has suppressed sending to this address because it has a recent history of bouncing as an invalid address. For more information about how to remove an address from the suppression list, see the Amazon SES Developer Guide: http://docs.aws.amazon.com/ses/latest/DeveloperGuide/remove-from-suppressionlist.html "
      }
    ],
    "timestamp": "2020-03-20T21:00:42.217Z",
    "feedbackId": "01070170f9bf8131-9cbe20b1-7997-4d33-8e02-7e828eb01edc-000000",
    "reportingMTA": "dns; amazonses.com"
  },
  "mail": {
    "timestamp": "2020-03-20T21:00:42.217Z",
    "source": "tester@####.com",
    "sourceArn": "arn:aws:ses:eu-central-1:425905684163:identity/####",
    "sourceIp": "54.239.6.46",
    "sendingAccountId": "425905684163",
    "messageId": "01070170f9bf8091-79e59712-3c2d-424c-9eba-3e221ef336ff-000000",
    "destination": [
      "blacklist@simulator.amazonses.com"
    ],
    "headersTruncated": false,
    "headers": [
      {
        "name": "From",
        "value": "tester@####.com"
      },
      {
        "name": "To",
        "value": "blacklist@simulator.amazonses.com"
      },
      {
        "name": "Subject",
        "value": "lkasnlkaslknaslkn"
      },
      {
        "name": "MIME-Version",
        "value": "1.0"
      },
      {
        "name": "Content-Type",
        "value": "text/plain; charset=UTF-8"
      },
      {
        "name": "Content-Transfer-Encoding",
        "value": "7bit"
      }
    ],
    "commonHeaders": {
      "from": [
        "*****"
      ],
      "to": [
        "blacklist@simulator.amazonses.com"
      ],
      "subject": "lkasnlkaslknaslkn"
    }
  }
}```
why should single value array? 

I give it a try now

**Comment by mabujaber** [comment]
Looks like a spring boot issue because I tried to register the java time module and run without spring it works fine.

**Comment by kupci** [comment]
Ok, that helps narrow it, I suppose this issue can be closed? 

Though it would still be interesting to know why it doesn't work out of the box for Spring Boot. Maybe a config issue with the way Spring is registering the Java time module? One possibility - are you using your own mapper or the default mapper?

https://codeboje.de/jackson-java-8-datetime-handling/

**Comment by mabujaber** [comment]
I can narrow it more, I'm using the default ObjectMapper. I tried to customized and register `JavaTimeModule` but no difference. I can point that I'm using `spring-coud-aws` for this purpose to consume the message in SQS queue I'm not sure whether spring using a different way of deserializers for this module.

I raise to spring-cloud-aws team and let see their response. 

Thanks

**Comment by srjha** [comment]
Not sure if this issue is resolved and that is the reason for closing this issue.
I faced it too with 2.3.4.RELEASE of spring boot today. Luckily, I could spot what made the difference.

I started to get this issue as soon as I extended RequestMappingHandlerAdapter for some other need somewhere else in code. And I kept wondering how can this make any difference!
However, as soon as I stop extending this class, everything is fine.

**Comment by cowtowncoder** [comment]
@srjha The issue assumed to be here -- not using Java 8 date/time module -- was closed. If that is your problem, you need to register the module: this is not something Jackson can do; it is up to Spring Boot to included it or not, and perhaps document the problem.

If you are facing issue other than this (discussion here seems to have gone over other aspects), you may want to file a new issue.
