### ISSUE TITLE
ZonedDateTime documentation seems to be incorrect

### ISSUE THREAD

**Issue by AceHack** [FasterXML/jackson-modules-java8#170]
It says:
https://github.com/FasterXML/jackson-modules-java8/tree/master/datetime

For string representation default formats for deserialization are:
|  Java type | Format  |
|------------|---------|
|[`ZonedDateTime`](https://docs.oracle.com/javase/8/docs/api/java/time/ZonedDateTime.html)|[`DateTimeFormatter.ISO_ZONED_DATE_TIME`](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#ISO_ZONED_DATE_TIME)|

But in the code I see:
https://github.com/FasterXML/jackson-modules-java8/blob/1534c557d4ea997b7a80a9bcba4c98cd558e4493/datetime/src/main/java/com/fasterxml/jackson/datatype/jsr310/ser/ZonedDateTimeSerializer.java#L22-L23

**Comment by kupci** [comment]
Yes, and the comment could be improved too. A little ambiguous though perhaps trying to explain why `ISO_OFFSET_DATE_TIME` is used and not `ISO_ZONED_DATE_TIME`,

**Comment by mydata** [comment]
@cowtowncoder please confirm
is the documentation need to be updated to match the implementation OR implementation has to match documentation?

**Comment by cowtowncoder** [comment]
@mydata Generally documentation should match implementation unless indicated otherwise. So I'd start with that.

**Comment by winfriedgerlach** [comment]
@cowtowncoder as far as I can see the documentation was fixed a long time ago with https://github.com/FasterXML/jackson-modules-java8/commit/92c9e0dd1b6ed7a50bf6da316140e78533b138f7 and the code was also modified to include a more extensive comment why `ISO_OFFSET_DATE_TIME` is used. IMHO this ticket can be closed.
