### ISSUE TITLE
Can not serialize java 8 stream with StackOverflowError

### ISSUE THREAD

**Issue by ilumer** [FasterXML/jackson-modules-java8#174]
I try to use stream api to get all elements recursive, but this method throw a infinite recursion (StackOverflowError)。I can not find problem in my code，I try to build a small code to reproduce this scenario，I find the reason that produce error  is I register the `Jdk8Module`.
If i remove this module , it work right. Can you give me some suggestions, thank you.
* java version 1.8.0_162
* jackson-databind 2.9.0
* jackson-datatype-jdk8 2.9.0
```
public class Store {
  public static void main(String[] args) {
    ObjectMapper objectMapper = new ObjectMapper().registerModule(new Jdk8Module());
    ResponseData responseData = new ResponseData();
    List<a> list = new ArrayList<>();
    list.add(new a());
    responseData.data = list;
    try {
        responseData.getData();
      System.out.println(objectMapper.writeValueAsString(list));
    } catch (JsonProcessingException e) {
      System.out.println(e.toString());
    }
  }

  static class ResponseData {
    private List<a> data;

    public List<a> getData() {
      return data;
    }
  }

  static class a {

    private List<a> ele;

    public Stream<a> getEleStream() {
      if (CollectionUtils.isEmpty(ele)) {
        return Stream.of(this);
      } else {
        return Stream.concat(
            Stream.of(this), ele.stream().flatMap(a::getEleStream));
      }
    }
  }
}
```

**Comment by cowtowncoder** [comment]
But isn't your content here cyclic, with `a.elStream` pointing back to `a`? That would lead to infinite recursion. I am not sure how else it should work; either it is necessary to prevent cyclic references with `@JsonIgnore` on right fields, or to use Object Id handling (`@JsonIdentityInfo`).

As to including `jackson-datatype-jdk8`: without it `Stream` is only seen as POJO, probably with `parallel` (from `boolean isParallel()`).

**Comment by ilumer** [comment]
Thanks for replaying，I just think `Stream` is only seen as POJO, so  it should not throw  StackOverflowError. I should read the doc more carefully.
