### ISSUE TITLE
InstantDeserializer not working with offset +0800

### ISSUE THREAD

**Issue by bhushan2901** [FasterXML/jackson-modules-java8#179]
Hi , 

I have configured my ObjectMapper as below. 

```java
final ObjectMapper JSONMAPPER = new ObjectMapper();
JSONMAPPER.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
JSONMAPPER.registerModule(new JavaTimeModule());
```

working Case : 

```
String json = "\"2020-06-24T17:00:33.585+0000\"";
Instant test = JSONMAPPER.readValue(json, Instant.class);
```

Not working case: 

```
json =  "\"2020-06-24T17:00:33.585+0800\"";
test = JSONMAPPER.readValue(json, Instant.class);
```

Exception: 

```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.Instant` from String "2020-06-24T17:00:33.585+0800": Failed to deserialize java.time.Instant: (java.time.format.DateTimeParseException) Text '2020-06-24T17:00:33.585+0800' could not be parsed at index 23
 at [Source: (String)""2020-06-24T17:00:33.585+0800""; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1676)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:932)
	at com.fasterxml.jackson.datatype.jsr310.deser.JSR310DeserializerBase._handleDateTimeException(JSR310DeserializerBase.java:80)
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.deserialize(InstantDeserializer.java:212)
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.deserialize(InstantDeserializer.java:50)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3173)
```

**Comment by cowtowncoder** [comment]
What is the version of `jackson-datatype-jsr310` module?

**Comment by bhushan2901** [comment]
i have tried this with below versions. 
INFO]    com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.9.9:compile -- module com.fasterxml.jackson.datatype.jsr310 [auto]

INFO]    com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.11.1:compile -- module com.fasterxml.jackson.datatype.jsr310

In both the cases same behaviour observed. 

Thanks,
Bhushan.

**Comment by cowtowncoder** [comment]
Ok, this seems to be misunderstanding on use of `Instant`; it is NOT a full timezone-taking data type (like `ZonedDateTime`) but instant in time. As such, not being associated with timezone, input should only come in Zulu timezone -- this is why `+0000` (and `+00:00`) is allowed, although `Z` would be canonical representation.
You can see how `Instant.parse(value)` would fail similarly.

@kupci WDYT?

**Comment by kupci** [comment]
Agree, was just composing answer so I'll include a few links I had been putting together:

The [default format](https://github.com/FasterXML/jackson-modules-java8/tree/master/datetime) for string deserialization of `Instant` is [ISO_INSTANT](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#ISO_INSTANT), so for anything other than "+0000", (see [tests cases](https://github.com/FasterXML/jackson-modules-java8/blob/67e06eec44ed94e6eeaf84e7eaca334120136141/datetime/src/test/java/com/fasterxml/jackson/datatype/jsr310/deser/InstantDeserTest.java#L412)) there is the `OffsetDateTime` which uses [ISO_OFFSET_DATE_TIME](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#ISO_OFFSET_DATE_TIME), would that work for you?

**Comment by kupci** [comment]
_input should only come in Zulu timezone -- this is why +0000 (and +00:00) is allowed, although Z would be canonical representation._

Zulu - had been wondering what the "Z" stood for. Learn something new every day :)
https://www.timeanddate.com/time/zones/z

**Comment by bhushan2901** [comment]
Hi @kupci , @cowtowncoder
Thanks for response , sorry for delay. Yes Instant.parse(value) fails with both +0000 and +0800 , but as  first works with jackson module and other not thats got me confused.  as when I checked the code i see that we are replacing +0000 with Z I will try to use OffsetDateTime in my code .

**Comment by cowtowncoder** [comment]
Yes, that +0000/+00:00 translation can be pretty confusing here.
