### ISSUE TITLE
Override default formatter in JavaTimeModule

### ISSUE THREAD

**Issue by chkpnt** [FasterXML/jackson-modules-java8#181]
Is there a way to override the default formatter used in the `JavaTimeModule`? Using the `@JsonFormat`-annotation works fine, but I would like to setup the formatter where I instantiate my `ObjectMapper`.

I know I can simply register my own `JsonDeserializer`, but I would prefere to keep using the already existing implementation, so I could still use `@JsonFormat` where necessary.

**Comment by kupci** [comment]
It is supported for certain types: `LocalDate`, `LocalDateTime`, `LocalTime`, `YearMonth`, `Year`, and `ZonedDateTime`. You can see an example of how to implement it in the tests, for example: 

 ```
   @Test
    public void testDeserialization() throws Exception {
        LocalDate date = LocalDate.now();
        assertThat(deserializeWith(date.format(formatter), formatter), equalTo(date));
    }

    private LocalDate deserializeWith(String json, DateTimeFormatter f) throws Exception {
        ObjectMapper mapper = JsonMapper.builder()
                .addModule(new SimpleModule()
                        .addDeserializer(LocalDate.class, new LocalDateDeserializer(f)))
                .build();
        return mapper.readValue("\"" + json + "\"", LocalDate.class);
    }
```
https://github.com/FasterXML/jackson-modules-java8/blob/59df861f2a6396f782f3099cc681dc4df2e55096/datetime/src/test/java/com/fasterxml/jackson/datatype/jsr310/ser/TestLocalDateSerializationWithCustomFormatter.java#L45

Is that what you are looking for?

**Comment by chkpnt** [comment]
Yeah, this is exactly what I'm doing right now:

```java
  public ObjectMapper create()
  {
    JavaTimeModule javaTimeModule = new JavaTimeModule();
    javaTimeModule.addDeserializer(LocalDate.class, new GermanDateDeserializer());
    
    return new ObjectMapper()
        .registerModule(new Jdk8Module())
        .registerModule(javaTimeModule)
        .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
        .configure(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE, true);
  }
```

But as I've seen the following in the code of the already existing deserializers: 

https://github.com/FasterXML/jackson-modules-java8/blob/59df861f2a6396f782f3099cc681dc4df2e55096/datetime/src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/JSR310DateTimeDeserializerBase.java#L77

[`StdDeserializer.java`](https://github.com/FasterXML/jackson-databind/blob/e4b68d86e5319d5262b5f0a03a356ace4d24016e/src/main/java/com/fasterxml/jackson/databind/deser/std/StdDeserializer.java#L1426-L1434):
```java
    protected JsonFormat.Value findFormatOverrides(DeserializationContext ctxt,
            BeanProperty prop, Class<?> typeForDefaults)
    {
        if (prop != null) {
            return prop.findPropertyFormat(ctxt.getConfig(), typeForDefaults);
        }
        // even without property or AnnotationIntrospector, may have type-specific defaults
        return ctxt.getDefaultPropertyFormat(typeForDefaults);
    }
```

As far as I understood this is to read the `@JsonFormat`-annotation. I just havn't understood yet if this `ctxt` can (already) be configured somehow else.

**Comment by chkpnt** [comment]
Ah, oh.... sorry, now I get it, what you've written! You are suggesting to just instantiate the `LocalDateDeserializer` with the formatters I need. Yeah, this could work. I'll try it out.

**Comment by chkpnt** [comment]
Yes, I can confirm, it's working fine. My `ObjectMapper` is now using a custom default but still be able to use the `@JsonFormat`-Annotations. Thanks for the hint!

```java
public class ObjectMapperFactory
{
  
  private static final DateTimeFormatter GERMAN_DATE_FORMATTER = DateTimeFormatter.ofPattern("dd.MM.yyyy");

  public ObjectMapper create()
  {
    JavaTimeModule javaTimeModule = new JavaTimeModule();
    javaTimeModule.addDeserializer(LocalDate.class, new LocalDateDeserializer(GERMAN_DATE_FORMATTER));
    
    return new ObjectMapper()
        .registerModule(new Jdk8Module())
        .registerModule(javaTimeModule)
        .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
        .configure(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE, true);
  }
}
```

**Comment by kupci** [comment]
Glad it worked out - wasn't exactly sure it would work as you required, thanks for confirming.

**Comment by cowtowncoder** [comment]
I would actually recommend a different mechanism, so-called "Config overrides", since use of actual (de)serializers directly is actually not part of supported API (it may work, but might not and may break with newer versions).

Usage with 2.x is like so:

```java
ObjectMapper mapper = ...;
mapper.configOverride(LocalDateTime.class)
    .setFormat(JsonFormat.Value.forPattern("yyyy+MM+dd");   
```

The main reason why this is preferred is simply that the mechanism of construction of (de)serializers may change as it is considered part of internal API.

**Comment by chkpnt** [comment]
Yeah, that is indeed the solution I was looking for in the first place. Thanks for pointing that out!
