### ISSUE TITLE
Mapping a present Optional returns an empty Optional

### ISSUE THREAD

**Issue by carlwitt** [FasterXML/jackson-modules-java8#182]
Jackson 2.11 seems to always return `Optional.empty` when the entire object to be mapped is an Optional (not just one of its fields). The problem appears in the following code:
```
protected <R> R convertResult(final Object response, final Object valueType) {
    JavaType constructType = TypeFactory.defaultInstance().constructType((Type)valueType);
    Object convertValue = objectMapper.convertValue(value, constructType);
    // convertValue equals Optional.empty here
```
When stepping through the code, the problem appears with the following values
- objectMapper has Jdk8Module registered
- valueType = `ParameterizedTypeImpl java.util.Optional<SourceError>`
- constructType = `[simple type, class java.util.Optional<SourceError>]`
- SourceError = `class SourceError { public int line; public String message; }`
- value = UnmodifiableMap containing two entries `{message=For input string: "1long.line", line=1}`

However, catching the case where the entire object is an Optional (not just one of its fields) with the following code fixes my problem:
```
ParameterizedType parameterizedType = (ParameterizedType)valueType;
Class<?> innerType = (Class<?>) parameterizedType.getActualTypeArguments()[0];
Object convertValue = objectMapper.convertValue(jsonRpcResponse.getResult(), innerType);
if(convertValue == null) {
    return (R) Optional.empty();
} else {
    return (R) Optional.of(convertValue);
}
```
It looks like a bug to me.

**Comment by cowtowncoder** [comment]
I think I would need a full reproduction here, to know what to think. It is possible that combination of `Optional` and `convertValue()` do not work well, but there is also question of Java Type Erasure (runtime type of `Optional` values does not contain useful parameterization unfortunately).

**Comment by cowtowncoder** [comment]
No way to reproduce the issue, closing. May be reopened with a test case or equivalent.
