### ISSUE TITLE
NoSuchMethodError on JSR310DateTimeDeserializerBase.findFormatOverride -- checked for version incompatibilities

### ISSUE THREAD

**Issue by jlevers** [FasterXML/jackson-modules-java8#193]
I installed the JSR310 datatype package by adding the below to my `build.gradle`.

```
compile group: 'com.fasterxml.jackson.datatype', name: 'jackson-datatype-jsr310', version: '2.9.5'
```

Once I did so, I started getting the following error on every `POST` endpoint on my `spring-webmvc` application:

```
Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: 'com.fasterxml.jackson.annotation.JsonFormat$Value com.fasterxml.jackson.datatype.jsr310.deser.JSR310DateTimeDeserializerBase.findFormatOverrides(com.fasterxml.jackson.databind.DeserializationContext, com.fasterxml.jackson.databind.BeanProperty, java.lang.Class)'
```

I followed the advice I found here to remove incompatible extra versions of `jackson` on my classpath, which I did -- I had `2.11.2` installed as well. I removed it, and when this problem persisted, I `grep`ed my home folder and removed every trace of that version I could find (from `~/.m2`, `~/.gradle/caches`, and my `tomcat` installation). Despite that, I'm still getting the same error. I also tried both downgrading and upgrading from `2.9.5` to `2.8.9` and `2.11.2`, cleaning out all traces of other versions of the package each time.

When I run `./gradlew dependencies | grep jackson`, all versions of Jackson-related packages are between `2.9.0` and `2.9.5`.

Any idea what's going on here? I've been trying to figure this out for more than a day, and I'm not sure what to try next. Thank you.

**Comment by cowtowncoder** [comment]
That is odd. Method itself is defined in `StdDeserializer` from "jackson-databind", added in Jackson 2.7.

My guess is that there is a copy of `jackson-databind` jar in classpath, much older version than 2.9.

I suspect there should not be reason to use `2.9.5`, btw; I would try with latest 2.9, `2.9.10`.
But that alone probably would not explain the issue.

**Comment by jlevers** [comment]
Interesting, I'll try the latest 2.9, but I agree that that probably won't solve the issue. I'm just not sure how to find the extraneous version(s) of `jackson-databind` since `grep`ing my system doesn't get me anything that seems wrong, and no extra versions of `JSR310DateTimeDeserializerBase` show up when I search available types in Eclipse. I'll keep hunting, though -- thanks!

**Comment by cowtowncoder** [comment]
@jlevers good luck! These are nasty, and I guess it could even be something more complicated -- sometimes there can be transitive fails... in this case, if `jackson-annotations` were missing, for example, from classpath. But that seems unlikely too, should fail for databind already.

**Comment by kupci** [comment]
Likely that Spring is overriding the config settings, so you'd have to do something similar to what is described here, to exclude / include as needed. This is specifically for Spring Boot / Maven but should apply to Spring / Gradle too. 

> The Spring Boot parent POM includes Jackson dependencies. When you include the version number, it overrides the Spring Boot curated dependency versions. Therefore, you may encounter version conflicts.
https://springframework.guru/processing-json-jackson/

> But what if we want to use a newer version of Jackson? The proper way is to exclude the inherent dependencies, and explicitly add their new versions,

https://springframework.guru/jackson-dependency-issue-spring-boot-maven/

**Comment by jlevers** [comment]
I found the issue (although I haven't figured out how to fix it)...there's a local jar that I'm including that has `jackson-databind:2.6.7` in it. When I switched to `jackson-databind:2.9.10`, per @cowtowncoder's suggestion, I got a new (but similar) error:

```
java.lang.NoSuchMethodError: 'void com.fasterxml.jackson.core.JsonGenerator.writeStartObject(java.lang.Object)'
```

In the process of trying to track that down, I discovered there were two `JsonGenerator` classes on my classpath, and the older one was inside that local jar.

For anyone else who runs into this issue -- you can't resolve it in the `build.gradle` or `pom.xml` files of the project from which you're requiring the local jar. You have to exclude the old dependency from the `build.gradle` or `pom.xml` file of the package that you built the local jar from. Here's what I mean:

I tried to remove the older version of `jackson-databind` by adding something like this to my primary `build.gradle`:
```
compile (files('path/to/local.jar')) {
	exclude group: 'com.fasterxml.jackson.core', module: 'jackson-databind'
}
```

That didn't work. What worked was excluding the old version of `jackson-databind` from the original `pom.xml` for the local jar I was using. In my case, that looked like this:

```
<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-signer</artifactId>
    <version>1.11.610</version>

    <exclusions>
	<exclusion>
	    <groupId>com.fasterxml.jackson.core</groupId>
	    <artifactId>jackson-databind</artifactId>
	</exclusion>
    </exclusions>
</dependency>
```

Then I rebuilt the local jar with `mvn package`, and referenced that new jar from my `build.gradle`.

Thank you @cowtowncoder and @kupci for your help!

**Comment by cowtowncoder** [comment]
@jlevers glad you were able to solve the issue, and thank you very much for documenting it to help others!
