### ISSUE TITLE
In 2.11.4 set [pattern = "yyyy-MM-dd"] in @JsonFormat cannot deserialize a valid LocalDate.

### ISSUE THREAD

**Issue by Fatezhang** [FasterXML/jackson-modules-java8#199]
__Hi there, I'm using SpringBoot 2.4.2 which Jackson version is 2.11.4, got an issue:__

When I set the `lenient` to false, the string `2021-01-18` cannot be deserialized to a LocalDate, see:

```java
    @JsonFormat(pattern = "yyyy-MM-dd", lenient = OptBoolean.FALSE)
    private LocalDate localDate;
```
and then I send the data in request body like:
```shell
curl -L -X GET 'http://localhost:8080/test' \
-H 'Content-Type: application/json' \
--data-raw '{
    "localDate": "2020-01-18"
}'
```
It shows
```
... could not be parsed: Unable to obtain LocalDate from TemporalAccessor: ...
```
But when I set it to `TRUE` or remove the annotation, it works.
I think set `lenient` to false means using strict mode, but `2020-01-18` should be a valid LocalDate, am I wrong?

---

Found an issue but not sure whether it related:
 #148 

---

## Update

`@JsonFormat(pattern = "yyyy-MM-dd", lenient = OptBoolean.FALSE)` cannot work,

__but__

`@JsonFormat(lenient = OptBoolean.FALSE)` works.

Could someone help to explain this behaviour? 
The above issue is in version `2.11.4`(or 2.11), but when I downgrade the version to `2.10.2`, `@JsonFormat(pattern = "yyyy-MM-dd", lenient = OptBoolean.FALSE)` works when I pass  `{"localDate": "2020-01-18"}`.

**Comment by cowtowncoder** [comment]
Since there is a difference between versions, it sounds like there might be a problem. If possible, it'd be good to see if 2.12.1 works or not; but most importantly it'd be great to have an actual unit test based on description above.

**Comment by Fatezhang** [comment]
Ah....... I found the actual reason.

The pattern should be `uuuu-MM-dd`.

Java 8 uses 'uuuu' for year, not 'yyyy' . In Java 8, 'yyyy' means “year of era” (BC or AD). See [here](https://howtodoinjava.com/java/date-time/resolverstyle-strict-date-parsing/).

The issue is related to this change in PR[#148] [here](https://github.com/FasterXML/jackson-modules-java8/blob/6dbff946196390f9bacf4f5478be2b6782c215ef/datetime/src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/JSR310DateTimeDeserializerBase.java#L120).

We made the `DateTimeFormatter` with `ResolverStyle.STRICT`,  not allow the `yyyy` for the YEAR anymore.
