### ISSUE TITLE
Allow `LocalDate` to be serialized/deserialized as number (epoch day)

### ISSUE THREAD

**Issue by kewne** [FasterXML/jackson-modules-java8#20]
The `LocalDateSerializer` only supports serializing `LocalDate` instances as strings or arrays, both of which suffer from localization issues ("is it year-month-day or year-day-month?").

An alternative would be to use `LocalDate#toEpochDay()` and `LocalDate#ofEpochDay(long)`, thus allowing a (less human readable but) unambiguous format.

**Comment by kewne** [comment]
Yep, both serialization and deserialization should be supported, and using `shape=Shape.Number` too.

I've forked the repo to try to work on this myself but the build fails with missing poms, is there a specific layout that's needed for building?

**Comment by kevinjom** [comment]
@kewne in my experience, clone the [jackson-bom](https://github.com/FasterXML/jackson-bom) repo, run `mvn clean install` and then go back to this repo, run whatever you want.

**Comment by kewne** [comment]
@kevinjom Got it working, thanks!

@cowtowncoder I'm looking through the code but I'm having difficulty understanding the rationale behind some of the formatting: some zeroes are added to the fractional part of the result "to avoid interpretation as integral number".
I've also found FasterXML/jackson-datatype-jsr310#67 which references something similar, what's the desired format?

**Comment by cowtowncoder** [comment]
@kewne excellent! I did not write this module originally, so some of the logic predates my changes. I don't recall part about additional zeroes, which should not be necessary to just differentiate between JSON integers vs floating-point numbers.

**Comment by cowtowncoder** [comment]
As per notes on PR, will merge as soon as we get CLA; will make it in 2.9(.0.pr3)
