### ISSUE TITLE
Integration of jackson-modules-java8 into OSS-Fuzz

### ISSUE THREAD

**Issue by onionpsy** [FasterXML/jackson-modules-java8#243]
Hi all,

We would like to integrate jackson-modules-java8 into OSS-Fuz like we have already done for the other jackon-* libraries. If you are also interested, can I use the same contact mail as for the [others](https://github.com/FasterXML/jackson-databind/issues/3454)?

**Comment by cowtowncoder** [comment]
Sure, yes.

**Comment by cowtowncoder** [comment]
Hi @onionpsy! Do you have a link to the new OSS-fuzz project for Java 8 modules?
