### ISSUE TITLE
*Serializer ignores format pattern if nano-second serialization enabled

### ISSUE THREAD

**Issue by Sam-Kruglov** [FasterXML/jackson-modules-java8#248]
Copying from the previous issue #224 

The following example has been fixed but you can try replacing `Duration` with `Instant` or any other temporal type to check if the issue reproduces or not:

```java
class MyDto {
  @JsonFormat(pattern = "MINUTES")
  @JsonProperty("durationInMins")
  private final Duration duration;

  public MyDto(Duration d) { duration = d; }

  public Duration getDuration() { return duration; }
}

var mapper = new ObjectMapper().findAndRegisterModules();
Map<String, Object> map = mapper.convertValue(new MyDto(Duration.ofHours(2)), new TypeReference<>(){});
assertEqual(map.get("durationInMins"), 120);
```

_Originally posted by @Sam-Kruglov in https://github.com/FasterXML/jackson-modules-java8/issues/224#issuecomment-882194448_

**Comment by cowtowncoder** [comment]
Thank you @Sam-Kruglov !

**Comment by cowtowncoder** [comment]
Hmmh. Does that code actually work? This:

    new TypeReference<>(){}

should be illegal as it has no type information.

**Comment by cowtowncoder** [comment]
That example does not compile, and I am not sure what it's supposed to do.

I think I'll just close this issue -- as entered it makes no sense.

New ones may be opened with specific reproduction, instead of outlining approach of someone finding issues.

**Comment by Sam-Kruglov** [comment]
@cowtowncoder hey, I don't actually remember what I meant by `Instant` having similar issues, I just tried to poke around it and couldn't find anything, the `pattern` seems to work fine. Also, the above example compiles and runs on JDK 11 with no problems, maybe you tried JDK 8? And yes, I can use diamond notation in the type reference as it fills the type in from the declaration.

Thanks for looking into it!

**Comment by cowtowncoder** [comment]
@Sam-Kruglov Ok yes, I do build with Java 8. Good to know it might actually work later on. Should have thought this might be it. Learned something new :-)

Also yeah, I can see that `Map` was solely for convenience of testing. But it did get me thinking into "Duration as Map key" which is actually another missing piece of functionality. But you are right, that's not what test did.

And I think there may well still be issues for maybe other types so we can open issues once they are encountered.

Same goes for Duration-as-Map-key (and others).
