### ISSUE TITLE
Wrong module auto-registered when using JPMS

### ISSUE THREAD

**Issue by karbi** [FasterXML/jackson-modules-java8#259]
As I understand module `com.fasterxml.jackson.datatype.jsr310.JSR310Module` is left for compatibility and `com.fasterxml.jackson.datatype.jsr310.JavaTimeModule` should be default one. However when using `ObjectMapper.findAndRegisterModules()` with JPMS in Java9+ `JSR310Module` is loaded as declared in module-info.java.

It should be changed as in #126 to maintain same behavior between modularized and non-modularized environments.

**Comment by cowtowncoder** [comment]
Merged in 2.15 branch to be included in 2.15.0.
