### ISSUE TITLE
JsonFormat.Feature.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS not respected when deserialising Instants

### ISSUE THREAD

**Issue by pmahony893** [FasterXML/jackson-modules-java8#272]
I have a class as follows:

```java
public class InstantWrapper {
    @JsonFormat(without = Feature.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS)
    private Instant myInstant;

    public Instant getMyInstant() { return myInstant; }
    public void setMyInstant(Instant myInstant) { this.myInstant = myInstant; }
}
```

When serialising, the result uses milliseconds since the epoch; however, when deserialising, it is interpreted as nanoseconds.

I understand that the JavaDoc says "Override for `SerializationFeature.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS`" (saying nothing about `DeserializationFeature.READ_DATE_TIMESTAMPS_AS_NANOSECONDS`), however in my view it's undesirable that a round-trip modifies the data when this option is used.

Is there a way (other than writing my own deserialiser) to override the ObjectMapper's settings so that timestamps are interpreted using milliseconds?

**Comment by cowtowncoder** [comment]
So does `DeserializationFeature.READ_DATE_TIMESTAMPS_AS_NANOSECONDS` not work? Or is this about there not being `JsonFormat.Feature.READ_DATE_TIMESTAMPS_AS_NANOSECONDS` to go with write option?

If latter, contributions for adding support would be most welcome: I think its missing is an omission; new per-property Features are added over time as requested.

**Comment by cowtowncoder** [comment]
Correct, a change would be needed in `jackson-annotations`. As to non-java.time (mostly Joda), I don't think this is supported outside java.time types, so it'd be enough to add support here.
For plumbing, looking at serialization side should be helpful; this would not necessarily be super difficult.

One thing is timing: if `jackson-annotations` change was contributed Really Soon Now (in next couple of days), I could merge that in for 2.15.0; and support could be added in one of 2.15.x versions for date/time module.
But annotations changes only go in .0 version so if not now, it'll need to go in 2.16.x which will take a while.

**Comment by cowtowncoder** [comment]
Ok, since it's just a small thing I went ahead and did https://github.com/FasterXML/jackson-annotations/issues/221 -- so there is now `JsonFormat.Feature.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS`.
I'll see how easy it'd be to do the rest now...

**Comment by cowtowncoder** [comment]
Ok. So, good news is that `JSR310DateTimeDeserializerBase` actually gets `JsonFormat.Value` already, through which newly added `JsonFormat.Feature` is readily accessible. Method `_withFormatOverrides()` is called with it.

The bad news is that plumbing may get bit hairy: looks like at least 4 deserializer implementations support nano-second format; ideally handling would be shared to some degree...

**Comment by cowtowncoder** [comment]
Lol. Looking at `DurationDeserializer`... meaning of "READ_DATE_TIMESTAMPS_AS_NANOSECONDS" is absolutely crazy -- it's taken to mean "read as SECONDS". I can't even. What happened there?

**Comment by cowtowncoder** [comment]
At this point I do not have time to work on this unfortunately: I can help if someone has time & itch; all pieces are ready (ability to override reading with `JsonFormat.Feature.READ_DATE_TIMESTAMPS_AS_NANOSECONDS`) so it should be doable, I just do not have bandwidth myself at this point.

**Comment by raman-babich** [comment]
JFYI, working on pr.
