### ISSUE TITLE
Milliseconds timestamps not parsing correctly for `LocalDate` even with `READ_DATE_TIMESTAMPS_AS_NANOSECONDS` as FALSE

### ISSUE THREAD

**Issue by ibrahimatcha** [FasterXML/jackson-modules-java8#283]
An example is trying to parse a field with an epoch millisecond value of 1532908800000 to a LocalDate. I get the error:

`com.fasterxml.jackson.databind.JsonMappingException: Invalid value for EpochDay (valid values -365243219162 - 365241780471): 1532908800000`

I have `READ_DATE_TIMESTAMPS_AS_NANOSECONDS` turned off in my configuration and set my object mapper bean to primary so spring doesn't override it but the issue persists. For some reason it keeps going back to the `LocalDateDeserializer` method that uses `ofEpochDay` and I cannot figure out why.

**Comment by cowtowncoder** [comment]
Cannot help without stand-alone reproduction, without Spring dependency.
For help with Spring configuration please reach out to Spring (Boot) communities instead.

Put another way, please try to reproduce with a stand-alone test, include here, first.

**Comment by ibrahimatcha** [comment]
Apologies @cowtowncoder, I've replicated it in [this codebase](https://github.com/ibrahimatcha/jackson-time-issue-replication) for you, let me know if what i have provided is still not adequate. 

Interestingly, zoneddatetime's are read just fine, it's localdate's that are the issue.

**Comment by cowtowncoder** [comment]
@ibrahimatcha Thank you for providing reproduction: that looks perfect!

It should help figure out the issue whenever someone has time to look into it (possibly me, eventually, if no one else has time).

**Comment by cowtowncoder** [comment]
For more convenient access, here's the code:

---------

```java
public class Time {

    private ZonedDateTime zonedDateTime;
    private LocalDate localDate;

    public ZonedDateTime getZonedDateTime() {
        return zonedDateTime;
    }

    public void setZonedDateTime(ZonedDateTime zonedDateTime) {
        this.zonedDateTime = zonedDateTime;
    }

    public LocalDate getLocalDate() {
        return localDate;
    }

    public void setLocalDate(LocalDate localDate) {
        this.localDate = localDate;
    }
}
```

```java
public class TimeTest {

    @Test
    void name() throws JsonProcessingException {
        Time expectedTime = new Time();
        expectedTime.setZonedDateTime(ZonedDateTime.ofInstant(Instant.ofEpochMilli(1548236954181L), ZoneOffset.UTC));
        expectedTime.setLocalDate(LocalDate.ofInstant(Instant.ofEpochMilli(1532908800000L), ZoneOffset.UTC));
        ObjectMapper objectMapper = new ObjectMapper().registerModule(new JavaTimeModule())
                .disable(DeserializationFeature.READ_DATE_TIMESTAMPS_AS_NANOSECONDS)
                .disable(SerializationFeature.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS);

        String timeJson = "{\n" +
                "\"zonedDateTime\": 1548236954181,\n" +
                "\"localDate\": 1532908800000, \n " +
                "}";

        Time actualTime = objectMapper.readValue(timeJson, Time.class);
        assertEquals(expectedTime, actualTime);
    }
}
```

**Comment by cowtowncoder** [comment]
Ok, this is not a valid issue: `LocalDate`s are not timestamp-based -- they are DATEs, without Time part, for one.
They are also not physical in the sense that they have no TimeZone at all, being "local".

From JavaDocs: "This class does not store or represent a time or time-zone. "

As such, integer values may be used but only to store

```
date.toEpochDay()
```

This can be seen by using the usual diagnostics technique: try writing (serializing) value with settings, then reading that value. But, actually, README for `datetime`:

https://github.com/FasterXML/jackson-modules-java8/tree/2.16/datetime

points out that the default representation is actually a JSON Array.

Now: if you wanted to use timestamp-based serialization, you'd need to write custom (de)serializer -- or we'd need to provide configurability for `JavaTimeModule` to do that.
Adding support might be tricky, too, given the lack of TimeZone for timestamps: translation from timestamp to `LocalDate` would probably require assumption of UTC as "time zone" (it's not technically one) for constructing `ZonedDateTime` and extracting/converting `LocalDate` from that.

**Comment by cowtowncoder** [comment]
Since this is not a valid flag, will close -- `LocalDate` does not (or intend to) support reading/writing from/as millisecond timestamp, due to reasons explained above.

**Comment by ibrahimatcha** [comment]
Okay that makes sense thanks @cowtowncoder. I wrote a custom deserialiser anyway as a stop-gap but I will stick with this approach then if it isn't supposed to be expected behaviour. Thanks!

**Comment by cowtowncoder** [comment]
@ibrahimatcha Correct: for non-standard handling here (to support legacy use case or such), custom deserializer is needed. I don't see this as being supported in future.
