### ISSUE TITLE
Breaking change in `InstantDeserializer API between 2.15 and 2.16

### ISSUE THREAD

**Issue by haraldk** [FasterXML/jackson-modules-java8#286]
Version 2.16 seems to have introduced a breaking change in the API for `InstantDeserializer`.

Since 6 years ago…. And up until 2.15, the [InstantDeserializer constructor](https://github.com/FasterXML/jackson-modules-java8/blob/cc5b7f030be0b2ff9641b3f79e7be16e5b3078a6/datetime/src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/InstantDeserializer.java#L115C1-L121C42) looked like this:

```java
    protected InstantDeserializer(Class<T> supportedType,
            DateTimeFormatter formatter,
            Function<TemporalAccessor, T> parsedToValue,
            Function<FromIntegerArguments, T> fromMilliseconds,
            Function<FromDecimalArguments, T> fromNanoseconds,
            BiFunction<T, ZoneId, T> adjust,
            boolean replaceZeroOffsetAsZ)
```

However, since 2.16 and onwards, [it was changed](https://github.com/FasterXML/jackson-modules-java8/blob/badd731b300c42def95fc35bfaa3dc436f8e8796/datetime/src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/InstantDeserializer.java#L156C1-L165C6) to this:

```java
    protected InstantDeserializer(Class<T> supportedType,
            DateTimeFormatter formatter,
            Function<TemporalAccessor, T> parsedToValue,
            Function<FromIntegerArguments, T> fromMilliseconds,
            Function<FromDecimalArguments, T> fromNanoseconds,
            BiFunction<T, ZoneId, T> adjust,
            boolean replaceZeroOffsetAsZ,
            boolean normalizeZoneId,
            boolean readNumericStringsAsTimestamp
    )
```

Two new `boolean` parameters added.

This breaks our custom subclass, that no longer finds it `super` constructor. To make things worse for us, the subclass is shared between multiple projects, that use different versions of Jackson, so we can't just upgrade and fix it for the latest version...

Can we have the old version (with defaults for the missing parameters) back, please. 😀 

If you like, I can make a PR, I just need to figure out what the defaults should be.

**Comment by cowtowncoder** [comment]
@haraldk Apologies for this... although sub-classing of these (de)serializers is not an originally planned use case, I don't think you are the only developer(s) doing that (or just constructing instances directly as the case may be).

Yes, a PR for 2.16.1 would be accepted; adding old constructor back as `@Deprecated`, delegating to the new one adding in 2.16.0.
I think there are 2 constants added in that class to pass as values for `normalizeZoneId` and `readNumericStringsAsTimestamp`.
