### ISSUE TITLE
`java.time.DateTimeException` serialization fails

### ISSUE THREAD

**Issue by olibraga** [FasterXML/jackson-modules-java8#319]
This code (using version 2.17.2, 2.16.2 and 2.13.5): 
```
  ObjectMapper mapper = new JsonMapper().registerModule(new JavaTimeModule());
  JsonGenerator gen = mapper.createGenerator(System.out);
  gen.writeObject(new java.time.DateTimeException("dummy"));
```
will throw `InvalidDefinitionException` with message `Java 8 date/time type 'java.time.DateTimeException' not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling`
which is obviously wrong as JavaTimeModule is added above.

This can be fixed in `BeanUtil#checkUnsupportedType(JavaType)`
by for example changing line:
`  if (className.indexOf('.', 10) >= 0) {`
to:
`  if (className.indexOf('.', 10) >= 0 || className.equals("java.time.DateTimeException")) {`

**Comment by cowtowncoder** [comment]
Thank you for reporting this issue! I'll have to think of the best way to handle this.

**Comment by cowtowncoder** [comment]
Created https://github.com/FasterXML/jackson-databind/issues/4718 for jackson-databind change(s); this issue can remain to allow for adding tests on module side (if any needed)

**Comment by cowtowncoder** [comment]
Fixed via https://github.com/FasterXML/jackson-databind/issues/4718 for 2.18(.1).
