### ISSUE TITLE
Clean up release notes

### ISSUE THREAD

**Issue by winfriedgerlach** [FasterXML/jackson-modules-java8#322]
It's quite confusing if you stumble across [datetime/release-notes/VERSION](https://github.com/FasterXML/jackson-modules-java8/blob/master/datetime/release-notes/VERSION). `2.8.5 (not yet released)` seems to be wrong, also `Project: jackson-datatype-jsr310` does not seem to fit the folder name (though it fits the artifact name in `pom.xml`).

Please:
* either clarify that this VERSION file is outdated and add some kind of pointer to [release-notes/VERSION-2.x](https://github.com/FasterXML/jackson-modules-java8/blob/master/release-notes/VERSION-2.x) (and possibly remove the "not yet released" section)
* or get rid of the file completely and move its content to [release-notes/VERSION-2.x](https://github.com/FasterXML/jackson-modules-java8/blob/master/release-notes/VERSION-2.x)

**Comment by cowtowncoder** [comment]
Will add a note -- these do refer to old, standalone repository.

**Comment by cowtowncoder** [comment]
Added a note on obsoleteness, won't spend much time on something this old.

**Comment by winfriedgerlach** [comment]
@cowtowncoder wow, that was quick, amazing! Have a nice day!

**Comment by cowtowncoder** [comment]
Thanks! You too, @winfriedgerlach.
