### ISSUE TITLE
`Jdk8Serializer.findReferenceSerializer()` leads to `StackOverflowError` in 2.8.9

### ISSUE THREAD

**Issue by gmokki** [FasterXML/jackson-modules-java8#33]
The commit 4d71c27e made the `Jdk8Serializer.findReferenceSerializer` method to go into infinite recursion if the matched reference type is not found.

Before the commit the method returned `null`, I think the author intended to call `super.findReferenceSerializer` at the end like the code does in the `findSerializer` method.

Currently 2.8.9 release is unusable for code that registers `Jdk8Module`

**Comment by cowtowncoder** [comment]
Oh shoot. Yes, that's... not good.

Do you know if this might also be the case for 2.9.0.pr4?

**Comment by joschi** [comment]
@cowtowncoder Any chance to get this fix in a Jackson 2.8.x bugfix release?

**Comment by cowtowncoder** [comment]
@joschi It will be, once 2.8.10 is released:

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8.10

but I'll have to figure out when to take time to cut this release, most likely the final full 2.8 release now that 2.9.0 is out.
