### ISSUE TITLE
`ZonedDateTime` serialization with `@JsonFormat.pattern` never uses it while `WRITE_DATES_WITH_ZONE_ID` enabled

### ISSUE THREAD

**Issue by verve111** [FasterXML/jackson-modules-java8#333]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

Hi, I'm using JavaTimeModule() in my app with SerializationFeature.WRITE_DATES_WITH_ZONE_ID enabled and there's a strange thing:
When JsonFormat-annotation with *pattern* is added:
```
    static class SomeDto {
        @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss z")
        private ZonedDateTime time;
    }
```
Current object is always serialized as an ISO_ZONED_DATE_TIME, e.g. "2024-11-15T18:27:06.921054+01:00[Europe/Germany]", the pattern is not taken into account.
Could you give a hint if this is expected behaviour, thank you!  

### Version Information

2.18.1

### Expected behavior

{"time":"2024-12-02 16:30:00 CET"}

**Comment by pjfanning** [comment]
may be related to #330

**Comment by JooHyukKim** [comment]
#330 was about `JsonFormat.lenient` configuration, which we ended up adding more documentation on @JsonFormat itself.

Wrt issue here, I think class-level `@JsonFormat` configuration should override global `SerializationFeature.WRITE_DATES_WITH_ZONE_ID`. Probably #334 would fix the issue.

**Comment by JooHyukKim** [comment]
@cowtowncoder Is this closed? 👀

**Comment by cowtowncoder** [comment]
@JooHyukKim I did close it, yes. Is there remaining work?

**Comment by JooHyukKim** [comment]
Yeah I thought #334 would be related

**Comment by cowtowncoder** [comment]
Yes, closed due to #334 fixing this issue. Feel free to re-open issues if they are wrongly closed (with a note).

**Comment by JooHyukKim** [comment]
Yeah, was asking because the mentioned PR #334 is still open 👀

**Comment by cowtowncoder** [comment]
Whops. So I did not actually yet merge it. My bad, thank you for reminder @JooHyukKim  :)

**Comment by cowtowncoder** [comment]
Now merged.
