### ISSUE TITLE
custom deserialization with absent Optional returns null   

### ISSUE THREAD

**Issue by PeterZalando** [FasterXML/jackson-modules-java8#36]
When using a custom deserialization for an Optional field, then the absence of that field is returning `null` instead of `Optional.empty()`.

I reproduced with my own test method in the test class `OptionalTest.java`:

```java
    public void testWithCustomDeserializerIfOptionalAbsent() throws Exception
    {
        assertEquals(Optional.empty(), MAPPER.readValue("{}",
                CaseChangingStringWrapper.class).value);

        assertEquals(Optional.empty(), MAPPER.readValue(aposToQuotes("{'value':null}"),
                CaseChangingStringWrapper.class).value);
    }
```

The first check fails, because of Jackson setting the `value` field to `null`.

**Comment by cowtowncoder** [comment]
I can not reproduce this without your including rest of the code...
Which version is this with?

**Comment by PeterZalando** [comment]
@cowtowncoder the rest of the test code is in this very repo here: https://github.com/FasterXML/jackson-modules-java8/blob/master/datatypes/src/test/java/com/fasterxml/jackson/datatype/jdk8/OptionalTest.java

(let's say, I just added one method to "your" test class) 

Will it help if I push that to a branch and create a pull request?

**Comment by cowtowncoder** [comment]
Yes I think a PR would be an easy way -- I can more easily view the test, and assuming it is valid could merge it in too.

I assume this is reproducible with 2.9.0?

**Comment by PeterZalando** [comment]
@cowtowncoder I created the PR https://github.com/FasterXML/jackson-modules-java8/pull/37

Is it the expectation right that missing fields should lead to Optional.empty()?

**Comment by cowtowncoder** [comment]
No. Jackson has no way of knowing what is not included (except by spending more time and effort in tracking existence, with additional overhead) at this point. One exception, however, is that of Creator properties (constructor, factory method) -- their existence is actually tracked.

**Comment by cowtowncoder** [comment]
Thank you for PR, I hope to look into this soon.

**Comment by cowtowncoder** [comment]
Ok. Right, assumption is incorrect -- no handling will occur for missing value.
In such a case the best way is to simply assign value to `Optional` field in field declaration or constructor: it will not be overwritten if there is nothing coming in for that value.

**Comment by PeterZalando** [comment]
Finally I found the root cause of my misunderstanding. The deserialization was inconsistent amongst my POJOs.

I just realized that this is because of Lombok generating the `@ConstructorProperties` to the `@AllArgsConstructor`. Lombok does that even if the constructor is implicit by `@Builder`, and even if access level is set to `PRIVATE` explicitely.

Jackson calls this annotated constructor always with `Optional.empty()` values for all absent fields that are of type `Optional`. Even if the constructor is private. Hence my POJOs behave differently when defined with or without Lombok's `@AllArgsConstructor`.

Similar issues have been discussed last year already, e.g. https://github.com/FasterXML/jackson-databind/issues/618
Not sure, if someone actually realized before that the different behavior for `Optional` fields comes from Lombok's generated `@ConstructorProperties`.

**Comment by PeterZalando** [comment]
@cowtowncoder actually there *is* handling for missing values: when there is a constructor with `@ConstructorProperties`. This is the root cause of my inconsistencies (see my previous comment).

If that is be design then this issue can be closed.

**Comment by cowtowncoder** [comment]
Yes, there is special tracking for members coming via creators, since they must be buffered anyway (unlike field/setter assigned ones).
There is also an issue (quite old) for trying to extend optional handling of missing values to all properties.
Its implementation has not started, there is some hope it could be done with Jackson 3.x.

So I think it can be considered an implementation limitation at this point.

Will close.
