### ISSUE TITLE
How does one pull the "datetime" package binaries into a Maven/Gradle project?

### ISSUE THREAD

**Issue by steve-perkins** [FasterXML/jackson-modules-java8#40]
This source repository contains a "datetime" sub-project, which includes the JSR310 code migrated from its earlier (now deprecated) repo.  https://github.com/FasterXML/jackson-datatype-jsr310

However, the `datetime` package does NOT appear to be included in the binary version of the `com.fasterxml.jackson.module:jackson-modules-java8` library available on Maven Central.

Was this an accidental omission, or am I missing something here?  How does one utilize the `datetime` package binaries in a Maven/Gradel project?

**Comment by kevinjom** [comment]
I am not very clear of how the release is published, but if you take a look at https://github.com/FasterXML/jackson-modules-java8/blob/master/datetime/pom.xml#L9, it says:

```
 <groupId>com.fasterxml.jackson.datatype</groupId>
  <artifactId>jackson-datatype-jsr310</artifactId>
```

So I assume the subproject `datetime` is published using this coordinate.

In our projects, we declare the dependency as `compile('com.fasterxml.jackson.datatype:jackson-datatype-jsr310:${THE_VERSION}')`

**Comment by cowtowncoder** [comment]
@stefanbirkner `jackson-modules-java8` is the parent pom for java8 modules in this repo and should NOT be used by anyone directly. Just ignore its existence.
Just include actual datatype module as @kevinjom suggested.

**Comment by cowtowncoder** [comment]
@Eido95 Good point.
