### ISSUE TITLE
Documentation mistake on module auto-registration

### ISSUE THREAD

**Issue by feinstein** [FasterXML/jackson-modules-java8#48]
The javadoc on `JavaTimeModule` says:

> Note that as of 2.6, this module does NOT support auto-registration, because of existence of legacy version, {@link JSR310Module}.

and the documentation shows that auto-registration is an option, this should be removed then.

**Comment by cowtowncoder** [comment]
Thank you for reporting this. I'll have a look.

**Comment by cowtowncoder** [comment]
Ah. I think I see what is happening here. What comment is trying to say is that the module auto-registered will be `JSR310Module`, due to entry in: 

    src/main/resources/META-INF/services/com.fasterxml.jackson.databind.Module

and that is the default due to legacy reasons. So it is correct in a way, although badly phrased.

I will change this in 3.0 to use the new module.

**Comment by cowtowncoder** [comment]
Updated javadoc a bit; fixed registration for `master` (3.0.0-SNAPSHOT)

**Comment by feinstein** [comment]
Yeah, it was a bit badly phrased, but I understood it.

The problem I see is how the github documentation is. It doesn't explain that the legacy version is the one to be registered, it just says that the module can be auto-registered, so people will only know about this if they read the javadoc, the ones copying and pasting from the github website will get the legacy version without knowing.

**Comment by feinstein** [comment]
The documentation says:

Usage
Registering module
Starting with Jackson 2.2, Modules can be automatically discovered using the Java 6 Service Provider Interface (SPI) feature. You can activate this by instructing an ObjectMapper to find and register all Modules:

ObjectMapper mapper = new ObjectMapper();
mapper.findAndRegisterModules();
You should use this feature with caution as it has performance implications. You should generally create one constant ObjectMapper instance for your entire application codebase to share, or otherwise use one of ObjectMapper's findModules methods and cache the result.

If you prefer to selectively register this module, this is done as follows, without the call to findAndRegisterModules():

ObjectMapper mapper = new ObjectMapper();
mapper.registerModule(new JavaTimeModule());
After either of these, functionality is available for all normal Jackson operations.

**Comment by cowtowncoder** [comment]
Oh. I did not check github README, only Javadocs. Thanks for pointing this out.

**Comment by cowtowncoder** [comment]
Updated README as well. Let me know if that still does not make sense, and/or you have suggestions for improvement.

**Comment by feinstein** [comment]
There's a `;` on another line, don't know if this was on purpose to "close" the `ObjectMapper` create, but besides this, it all looks perfectly clear for me now, thank you for taking the time!
