### ISSUE TITLE
Change ParanamerModule in readme

### ISSUE THREAD

**Issue by raderio** [FasterXML/jackson-modules-java8#54]
Chante readme to use `ParanamerModule`
https://github.com/FasterXML/jackson-modules-java8/tree/master/parameter-names
Currently it is `ParameterNamesModule` in examples

**Comment by cowtowncoder** [comment]
Huh? I don't think that is correct: paranamer module is at:

https://github.com/FasterXML/jackson-modules-base/tree/master/paranamer

and what this repo has is `ParameterNamesModules` for Java 8.

**Comment by raderio** [comment]
Well, when I add https://mvnrepository.com/artifact/com.fasterxml.jackson.module/jackson-modules-java8/2.9.4
I can not find/import ParameterNamesModule
Can you please add to readme the maven/gradle dependency?

**Comment by cowtowncoder** [comment]
@raderio And you have tried to find it, looking at jar and so on? Including reading README that includes Maven settings? (I don't use Gradle so I don't know, but I think it uses standard Maven coordinates).
