### ISSUE TITLE
Missing type ID in java.util.Optional return value in Spring REST controller method

### ISSUE THREAD

**Issue by steffen-harbich-itc** [FasterXML/jackson-modules-java8#59]
Please see my [Stackoverflow question](https://stackoverflow.com/questions/49071166). I have made [a simple example](https://www.dropbox.com/s/719poeehq6z05ac/demo-49071166.zip?dl=0) demonstrating the problem (Spring boot 2, gradle build, call test task). When using Optional as return value of Spring REST controller method then the type ID is not included in the Json response and the client complains about that:

> Missing type id when trying to resolve subtype of [simple type, class com.example.demo.MySubEntity]: missing type id property 'clazz'

Version is 2.9.4. Maybe this is not an issue with the jdk8 module but with Spring REST, I am not sure.

**Comment by cowtowncoder** [comment]
Ok, I'd need a reproduction that does not:

1. Require Spring
2. build using Gradle (stand-alone class is fine)

to be able to help here.
