### ISSUE TITLE
Single argument constructor with single parameter does not work ?

### ISSUE THREAD

**Issue by sylvainlecoy** [FasterXML/jackson-modules-java8#8]
Hi,

I have a case where I want to create an immutable object through constructor. The problem I found is that it get passed a null value first, then after try to set the field with the correct one, is this intended behavior ?

Here is a simple test to help you understand the problem:

```
public class JacksonTest {

    @Test
    public void TestReadValue() throws IOException {
        ObjectMapper objectMapper = new ObjectMapper()
                .setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY)
                .setVisibility(PropertyAccessor.CREATOR, JsonAutoDetect.Visibility.PUBLIC_ONLY)
                .registerModule(new ParameterNamesModule(JsonCreator.Mode.PROPERTIES));

        ImmutableIdentity identity = objectMapper.readValue("{\"id\":\"ABCDEF\"}", ImmutableIdentity.class);

        assertEquals("ABCDEF", identity.id);
    }

    private static final class ImmutableIdentity {

        private final String id;

        public ImmutableIdentity(final String id) {
            Objects.requireNonNull(id, "The id must not be null.");

            this.id = id;
        }
    }

}
```

Here is the stack

> com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of JacksonTest$ImmutableIdentity, problem: The id must not be null.
>  at [Source: {"id":"ABCDEF"}; line: 1, column: 15]

If I comment the Objects.requiredNonNull, the test passes. But I need that in my constructor since its part of my serialized Domain Events.

Any help is welcome. Also if its not supported I can work on a patch if you give me some guidelines.

**Comment by sylvainlecoy** [comment]
I also noticed this passes:

```
public class JacksonTest {

    @Test
    public void TestReadValue() throws IOException {
        ObjectMapper objectMapper = new ObjectMapper()
                .setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY)
                .setVisibility(PropertyAccessor.CREATOR, JsonAutoDetect.Visibility.PUBLIC_ONLY)
                .registerModule(new ParameterNamesModule(JsonCreator.Mode.PROPERTIES));

        ImmutableIdentity identity = objectMapper.readValue("{\"id\":\"ABCDEF\"}", ImmutableIdentity.class);

        assertEquals("ABCDEF", identity.id);
    }

    private static final class ImmutableIdentity {

        private final String id;
        private final String test;

        public ImmutableIdentity(final String id, final String test) {
            Objects.requireNonNull(id, "The id must not be null.");

            this.id = id;
            this.test = test;
        }
    }

}
```

**Comment by sylvainlecoy** [comment]
I cross-posted on Stack-overflow: http://stackoverflow.com/questions/41243608/jackson-single-argument-constructor-with-single-argument-fails-with-parameternam

**Comment by kekbur** [comment]
Could you add a note about this single argument constructor legacy behavior to README.md?

It's very counter-intuitive to have classes with 2+ argument constructors work flawlessly and classes with 1 argument constructors produce the following exception:

`JsonMappingException: Can not construct instance of my.DtoClass: no suitable constructor found, can not deserialize from Object value (missing default constructor or creator, or perhaps need to add/enable type information?)`

**Comment by cowtowncoder** [comment]
PRs welcome.
