### ISSUE TITLE
Duration deserialization uses seconds instead of nanos?

### ISSUE THREAD

**Issue by hho** [FasterXML/jackson-modules-java8#9]
Hi,

I don't understand why `Duration`s get deserialized as seconds by default:
https://github.com/FasterXML/jackson-modules-java8/blob/master/datetime/src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/DurationDeserializer.java#L60

Shouldn't that line be `Duration.ofNanos(…)`? Or is the name of the flag just super confusing in this case?

Thanks!

**Comment by cowtowncoder** [comment]
@hho Usage and design questions belong to mailing list(s):

https://groups.google.com/forum/#!forum/jackson-user

I can't speak for original design reason, original author (and/or one of contributor) may be able to answer the question there, as well as possible follow-up discussion (I presume you would be interested in changing this).
