### ISSUE TITLE
Allow JDK8 Optional to use contentConverter

### ISSUE THREAD

**Issue by sdavids13** [FasterXML/jackson-modules-java8#97]
The `@JsonDeserialize` and `@JsonSerialize` should allow a `contentConverter` to operate on the class inside the wrapped Java `Optional` class. Right now the only support is for using `converter` but you end up writing twice the amount of Converters if you need to support both Optional and Non-Optional bindings.

**Comment by cowtowncoder** [comment]
This may be valid, but I think I'd just need an example to show intended usage.
